### ISSUE TITLE
simple 3-point stencils result in wrong translations

### ISSUE THREAD

**Issue by sdorkenw** [uwplse/stng#13]
I adjusted the simple example from the End-to-End example slightly to 

```fortran
SUBROUTINE tb_2(j, x_min, x_max)
  INTEGER :: x_min
  INTEGER :: x_max
  INTEGER :: j
  REAL(kind=8), DIMENSION(x_min: x_max) :: in, out

  DO j = x_min+1, x_max-1
    out(j) = 0.3 * in(j) + 0.5 * in(j-1) + 0.2 * in(j+1)
  END DO

END SUBROUTINE
```

and the ran the End-to-End example code line by line. This lead to

```
  out(j) = (((float)0.6) * in(j + 1));
```

in Halide. I suspected the loop boundaries to get kind of in the way and changed the code to

```fortran
SUBROUTINE tb_4(j, x_min, x_max)
  INTEGER :: x_min
  INTEGER :: x_max
  INTEGER :: j
  REAL(kind=8), DIMENSION(x_min: x_max) :: in, out

  DO j = x_min, x_max
    out(j) = 0.3 * in(j) + 0.5 * in(j-1) + 0.2 * in(j+1)
  END DO

END SUBROUTINE
```

which would lead to out of bounds array accesses. Nonetheless, the translation of this looks way different:

```
out(j) = (((((float)0.2) * in(j)) + (((float)0.2) * in(j - 1))) + (((float)0.2) * in(j + 1)));
```

Still, the factors are wrong, but the pattern is correct.

Am I missing something?

**Comment by akcheung** [comment]
`tb_4` is due to not using enough bits for sketch during synthesis. (Shoaib and I concluded that at least 3 bits are needed) We are still looking into `tb_2`

**Comment by sdorkenw** [comment]
If I understand that correctly you mean `--bnd-inbits` and `--bnd-cbits` in the `... stng_backend sketch ...` step, right?
I tested setting both to `3` and then to `4` for `tb_4`, but both runs resulted in the same halide code as before with them set to `2`.

**Comment by shoaibkamil** [comment]
I think @akcheung misspoke here: we're still looking into `tb_4`, which doesn't fit into our model and hence is unlikely to work.

For `tb_2`, it should work by increasing both `--bnd-inbits` and `--bnd-cbits` to 3.  I've verified that it produces the correct output from Sketch.

**Comment by akcheung** [comment]
Yes sorry I meant `tb_2` @sdorkenw

**Comment by sdorkenw** [comment]
I tested `tb_2` with both `3` and `4`. The pattern is now correct, but the factors are still wrong. Halide:
```
out(j) = (((((float)0.2) * in(j)) + (((float)0.2) * in(j - 1))) + (((float)0.2) * in(j + 1)));
```

How can this be fixed? I am also lacking the intuition for what the number of bites represent. For future stencils: how do they relate to the stencil pattern?

**Comment by shoaibkamil** [comment]
Fixed the underlying bug; @sdorkenw please try now.  

The # of bits for synthesis has to be large enough so that the sketch has meaningful constraints, but the time to synthesize scales ~exponentially with the number of bits.  So we try to run as few bits as possible; in many cases 2 bits is sufficient, but some do require 3.  In this case, the number of bits needed to be increased not because of the stencil pattern, but because of the loop bounds.

**Comment by sdorkenw** [comment]
Thank you! I tried it and it works with 3 bits.
