### ISSUE TITLE
Running the frontend on NAS MG tests fails

### ISSUE THREAD

**Issue by sdorkenw** [uwplse/stng#4]
Hi,
I built the `frontend` with `make` on a 32bit Ubuntu 14.04 setup (same as in the Dockerfile). Running the `frontend` on the Cloverleaf and stencilmark tests works fine, but it fails for the NAS MG benchmark. When running `make MG_stencil` in the `NPB3.2-SER`directory I get:

   ```
In file included from ./mg_loop0_halideglue.cpp:1:
./mg_loop0_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop6_halideglue.cpp:1:
./mg_loop6_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop15_halideglue.cpp:1:
./mg_loop15_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop12_halideglue.cpp:1:
./mg_loop12_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop1_halideglue.cpp:1:
./mg_loop1_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop2_halideglue.cpp:1:
./mg_loop2_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop10_halideglue.cpp:1:
./mg_loop10_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop11_halideglue.cpp:1:
./mg_loop11_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop9_halideglue.cpp:1:
./mg_loop9_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop8_halideglue.cpp:1:
./mg_loop8_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop14_halideglue.cpp:1:
./mg_loop14_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop13_halideglue.cpp:1:
./mg_loop13_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop5_halideglue.cpp:1:
./mg_loop5_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop3_halideglue.cpp:1:
./mg_loop3_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop4_halideglue.cpp:1:
./mg_loop4_halideglue.h:15: warning: extra tokens at end of #endif directive
In file included from ./mg_loop18_halideglue.cpp:1:
./mg_loop18_halideglue.h:15: warning: extra tokens at end of #endif directive
/usr/bin/ld: cannot open output file ../../bin/mg.W: No such file or directory
collect2: ld returned 1 exit status
make[2]: *** [MG_stencil_exe] Error 1
make[1]: *** [MG_stencil] Error 2
make: *** [MG_stencil] Error 2
   ```

**Comment by akcheung** [comment]
I wasn't able to reproduce your error or your warnings. I just updated `MG/Makefile` to build the prerequisites. Can you try again and let me know?

**Comment by sdorkenw** [comment]
Thank you.

Nothing changed for me. However, I realized that there is already a lot (apparently everything important) created before the error is raised. There is just no `../../bin`, not even close and I do not know where `${PROGRAM}` is getting that from. I now hard coded the output to `-o ../mg.W` and that works fine.

**Comment by akcheung** [comment]
You mean there is no `bin` directory or you got some other form of error? As long as `MG/stencil` is populated with the output files that should be fine.

**Comment by sdorkenw** [comment]
Right, there is no `bin` directory. `MG/stencil` is populated. 

I would however suggest to change `-lpthread -o ../${PROGRAM}` to `-lpthread -o ../mg.W` in `MG/Makefile` if  that works in your build, too.

**Comment by akcheung** [comment]
`PROGRAM` is defined in `sys/make.common`, which is included in `MG/Makefile` if you set `STNG_HOME` appropriately. And `PROGRAM` references `BINDIR` etc which are set in `config/make.def` and is included in `MG/Makefile` as well.

**Comment by sdorkenw** [comment]
My paths are fine and when assuming that `PROGRAM` is correct (and I can now see where it is coming from) simply the folder (`BINDIR`) or an `mkdir` is missing. 

I just added `mkdir -p ../$(BINDIR)` under `MG_stencil_exe` and that works fine.
